<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-dnc_numbers']['en-us'] = "DNC Numbers";
$text['title-dnc_numbers']['ar-eg'] = "";
$text['title-dnc_numbers']['de-at'] = "DNC Nummern"; //copied from de-de
$text['title-dnc_numbers']['de-ch'] = "DNC Nummern"; //copied from de-de
$text['title-dnc_numbers']['de-de'] = "DNC Nummern";
$text['title-dnc_numbers']['es-cl'] = "";
$text['title-dnc_numbers']['es-mx'] = "";
$text['title-dnc_numbers']['fr-ca'] = "";
$text['title-dnc_numbers']['fr-fr'] = "";
$text['title-dnc_numbers']['he-il'] = "";
$text['title-dnc_numbers']['it-it'] = "Numeri DNC";
$text['title-dnc_numbers']['nl-nl'] = "";
$text['title-dnc_numbers']['pl-pl'] = "";
$text['title-dnc_numbers']['pt-br'] = "";
$text['title-dnc_numbers']['pt-pt'] = "";
$text['title-dnc_numbers']['ro-ro'] = "";
$text['title-dnc_numbers']['ru-ru'] = "DNC Номеров";
$text['title-dnc_numbers']['sv-se'] = "DNC Nummer";
$text['title-dnc_numbers']['uk-ua'] = "";

$text['title-dnc_number']['en-us'] = "DNC Number";
$text['title-dnc_number']['ar-eg'] = "";
$text['title-dnc_number']['de-at'] = "DNC Nummer"; //copied from de-de
$text['title-dnc_number']['de-ch'] = "DNC Nummer"; //copied from de-de
$text['title-dnc_number']['de-de'] = "DNC Nummer";
$text['title-dnc_number']['es-cl'] = "";
$text['title-dnc_number']['es-mx'] = "";
$text['title-dnc_number']['fr-ca'] = "";
$text['title-dnc_number']['fr-fr'] = "";
$text['title-dnc_number']['he-il'] = "";
$text['title-dnc_number']['it-it'] = "Numero DNC";
$text['title-dnc_number']['nl-nl'] = "";
$text['title-dnc_number']['pl-pl'] = "";
$text['title-dnc_number']['pt-br'] = "";
$text['title-dnc_number']['pt-pt'] = "";
$text['title-dnc_number']['ro-ro'] = "";
$text['title-dnc_number']['ru-ru'] = "DNC Номер";
$text['title-dnc_number']['sv-se'] = "DNC Nummer";
$text['title-dnc_number']['uk-ua'] = "";

$text['title_description-dnc_number']['en-us'] = "List of DNC Numbers and Carrier codes.";
$text['title_description-dnc_number']['ar-eg'] = "";
$text['title_description-dnc_number']['de-at'] = "Liste von DNC Nummern und Kontoschlüssel."; //copied from de-de
$text['title_description-dnc_number']['de-ch'] = "Liste von DNC Nummern und Kontoschlüssel."; //copied from de-de
$text['title_description-dnc_number']['de-de'] = "Liste von DNC Nummern und Kontoschlüssel.";
$text['title_description-dnc_number']['es-cl'] = "";
$text['title_description-dnc_number']['es-mx'] = "";
$text['title_description-dnc_number']['fr-ca'] = "";
$text['title_description-dnc_number']['fr-fr'] = "";
$text['title_description-dnc_number']['he-il'] = "";
$text['title_description-dnc_number']['it-it'] = "Lista dei numeri DNC e degli Carrier codes.";
$text['title_description-dnc_number']['nl-nl'] = "";
$text['title_description-dnc_number']['pl-pl'] = "";
$text['title_description-dnc_number']['pt-br'] = "";
$text['title_description-dnc_number']['pt-pt'] = "";
$text['title_description-dnc_number']['ro-ro'] = "";
$text['title_description-dnc_number']['ru-ru'] = "Список DNC Номеров и Аккаунт кодов.";
$text['title_description-dnc_number']['sv-se'] = "Lista med DNC Nummer och Carrier codes.";
$text['title_description-dnc_number']['uk-ua'] = "";

$text['label-dnc_number']['en-us'] = "DNC Number";
$text['label-dnc_number']['ar-eg'] = "";
$text['label-dnc_number']['de-at'] = "DNC Nummer"; //copied from de-de
$text['label-dnc_number']['de-ch'] = "DNC Nummer"; //copied from de-de
$text['label-dnc_number']['de-de'] = "DNC Nummer";
$text['label-dnc_number']['es-cl'] = "";
$text['label-dnc_number']['es-mx'] = "";
$text['label-dnc_number']['fr-ca'] = "";
$text['label-dnc_number']['fr-fr'] = "";
$text['label-dnc_number']['he-il'] = "";
$text['label-dnc_number']['it-it'] = "Numero DNC";
$text['label-dnc_number']['nl-nl'] = "";
$text['label-dnc_number']['pl-pl'] = "";
$text['label-dnc_number']['pt-br'] = "";
$text['label-dnc_number']['pt-pt'] = "";
$text['label-dnc_number']['ro-ro'] = "";
$text['label-dnc_number']['ru-ru'] = "DNC Номер";
$text['label-dnc_number']['sv-se'] = "DNC Nummer";
$text['label-dnc_number']['uk-ua'] = "";

$text['description-dnc_number']['en-us'] = "Enter the DNC number.";
$text['description-dnc_number']['ar-eg'] = "";
$text['description-dnc_number']['de-at'] = "Geben Sie die DNC Nummer ein."; //copied from de-de
$text['description-dnc_number']['de-ch'] = "Geben Sie die DNC Nummer ein."; //copied from de-de
$text['description-dnc_number']['de-de'] = "Geben Sie die DNC Nummer ein.";
$text['description-dnc_number']['es-cl'] = "";
$text['description-dnc_number']['es-mx'] = "";
$text['description-dnc_number']['fr-ca'] = "";
$text['description-dnc_number']['fr-fr'] = "";
$text['description-dnc_number']['he-il'] = "";
$text['description-dnc_number']['it-it'] = "Inserire il DNC";
$text['description-dnc_number']['nl-nl'] = "";
$text['description-dnc_number']['pl-pl'] = "";
$text['description-dnc_number']['pt-br'] = "";
$text['description-dnc_number']['pt-pt'] = "";
$text['description-dnc_number']['ro-ro'] = "";
$text['description-dnc_number']['ru-ru'] = "Введите DNC номер.";
$text['description-dnc_number']['sv-se'] = "Ange DNC NUmret.";
$text['description-dnc_number']['uk-ua'] = "";

$text['label-carriercode']['en-us'] = "Carrier Code";
$text['label-carriercode']['ar-eg'] = "";
$text['label-carriercode']['de-at'] = "Kontoschlüssel"; //copied from de-de
$text['label-carriercode']['de-ch'] = "Kontoschlüssel"; //copied from de-de
$text['label-carriercode']['de-de'] = "Kontoschlüssel";
$text['label-carriercode']['es-cl'] = "";
$text['label-carriercode']['es-mx'] = "";
$text['label-carriercode']['fr-ca'] = "";
$text['label-carriercode']['fr-fr'] = "";
$text['label-carriercode']['he-il'] = "";
$text['label-carriercode']['it-it'] = "Carrier Code";
$text['label-carriercode']['nl-nl'] = "";
$text['label-carriercode']['pl-pl'] = "";
$text['label-carriercode']['pt-br'] = "";
$text['label-carriercode']['pt-pt'] = "";
$text['label-carriercode']['ro-ro'] = "";
$text['label-carriercode']['ru-ru'] = "Код Аккаунта";
$text['label-carriercode']['sv-se'] = "Carrier Code";
$text['label-carriercode']['uk-ua'] = "";

$text['description-carriercode']['en-us'] = "Enter the Carrier Code.";
$text['description-carriercode']['ar-eg'] = "";
$text['description-carriercode']['de-at'] = "Geben Sie den Kontoschlüssel ein."; //copied from de-de
$text['description-carriercode']['de-ch'] = "Geben Sie den Kontoschlüssel ein."; //copied from de-de
$text['description-carriercode']['de-de'] = "Geben Sie den Kontoschlüssel ein.";
$text['description-carriercode']['es-cl'] = "";
$text['description-carriercode']['es-mx'] = "";
$text['description-carriercode']['fr-ca'] = "";
$text['description-carriercode']['fr-fr'] = "";
$text['description-carriercode']['he-il'] = "";
$text['description-carriercode']['it-it'] = "Inserire l'Carrier Code.";
$text['description-carriercode']['nl-nl'] = "";
$text['description-carriercode']['pl-pl'] = "";
$text['description-carriercode']['pt-br'] = "";
$text['description-carriercode']['pt-pt'] = "";
$text['description-carriercode']['ro-ro'] = "";
$text['description-carriercode']['ru-ru'] = "Введите код Аккаунта.";
$text['description-carriercode']['sv-se'] = "Ange Carrier Code";
$text['description-carriercode']['uk-ua'] = "";

$text['label-enabled']['en-us'] = "Enabled";
$text['label-enabled']['ar-eg'] = "";
$text['label-enabled']['de-at'] = "Aktiviert"; //copied from de-de
$text['label-enabled']['de-ch'] = "Aktiviert"; //copied from de-de
$text['label-enabled']['de-de'] = "Aktiviert";
$text['label-enabled']['es-cl'] = "";
$text['label-enabled']['es-mx'] = "";
$text['label-enabled']['fr-ca'] = "";
$text['label-enabled']['fr-fr'] = "";
$text['label-enabled']['he-il'] = "";
$text['label-enabled']['it-it'] = "Abilitato";
$text['label-enabled']['nl-nl'] = "";
$text['label-enabled']['pl-pl'] = "";
$text['label-enabled']['pt-br'] = "";
$text['label-enabled']['pt-pt'] = "";
$text['label-enabled']['ro-ro'] = "";
$text['label-enabled']['ru-ru'] = "Включено";
$text['label-enabled']['sv-se'] = "Aktiverad";
$text['label-enabled']['uk-ua'] = "";

$text['description-enabled']['en-us'] = "Enable or Disable the DNC Number.";
$text['description-enabled']['ar-eg'] = "";
$text['description-enabled']['de-at'] = "Die DNC Nummer aktivieren und deaktivieren."; //copied from de-de
$text['description-enabled']['de-ch'] = "Die DNC Nummer aktivieren und deaktivieren."; //copied from de-de
$text['description-enabled']['de-de'] = "Die DNC Nummer aktivieren und deaktivieren.";
$text['description-enabled']['es-cl'] = "";
$text['description-enabled']['es-mx'] = "";
$text['description-enabled']['fr-ca'] = "";
$text['description-enabled']['fr-fr'] = "";
$text['description-enabled']['he-il'] = "";
$text['description-enabled']['it-it'] = "Abilita o Disabilita il numero DNC.";
$text['description-enabled']['nl-nl'] = "";
$text['description-enabled']['pl-pl'] = "";
$text['description-enabled']['pt-br'] = "";
$text['description-enabled']['pt-pt'] = "";
$text['description-enabled']['ro-ro'] = "";
$text['description-enabled']['ru-ru'] = "Включение и отключение DNC Номера.";
$text['description-enabled']['sv-se'] = "Aktivera eller inaktivera DNC Nummer.";
$text['description-enabled']['uk-ua'] = "";

$text['label-description']['en-us'] = "Description";
$text['label-description']['ar-eg'] = "";
$text['label-description']['de-at'] = "Beschreibung"; //copied from de-de
$text['label-description']['de-ch'] = "Beschreibung"; //copied from de-de
$text['label-description']['de-de'] = "Beschreibung";
$text['label-description']['es-cl'] = "";
$text['label-description']['es-mx'] = "";
$text['label-description']['fr-ca'] = "";
$text['label-description']['fr-fr'] = "";
$text['label-description']['he-il'] = "";
$text['label-description']['it-it'] = "Descrizione";
$text['label-description']['nl-nl'] = "";
$text['label-description']['pl-pl'] = "";
$text['label-description']['pt-br'] = "";
$text['label-description']['pt-pt'] = "";
$text['label-description']['ro-ro'] = "";
$text['label-description']['ru-ru'] = "Описание";
$text['label-description']['sv-se'] = "Beskrivning";
$text['label-description']['uk-ua'] = "";

$text['description-description']['en-us'] = "Enter the description.";
$text['description-description']['ar-eg'] = "";
$text['description-description']['de-at'] = "Geben Sie die Beschreibung ein."; //copied from de-de
$text['description-description']['de-ch'] = "Geben Sie die Beschreibung ein."; //copied from de-de
$text['description-description']['de-de'] = "Geben Sie die Beschreibung ein.";
$text['description-description']['es-cl'] = "";
$text['description-description']['es-mx'] = "";
$text['description-description']['fr-ca'] = "";
$text['description-description']['fr-fr'] = "";
$text['description-description']['he-il'] = "";
$text['description-description']['it-it'] = "Inserire la descrizione.";
$text['description-description']['nl-nl'] = "";
$text['description-description']['pl-pl'] = "";
$text['description-description']['pt-br'] = "";
$text['description-description']['pt-pt'] = "";
$text['description-description']['ro-ro'] = "";
$text['description-description']['ru-ru'] = "Введите описание.";
$text['description-description']['sv-se'] = "Ange beskrivningen.";
$text['description-description']['uk-ua'] = "";

$text['label-true']['en-us'] = "true";
$text['label-true']['ar-eg'] = "";
$text['label-true']['de-at'] = "ein"; //copied from de-de
$text['label-true']['de-ch'] = "ein"; //copied from de-de
$text['label-true']['de-de'] = "ein";
$text['label-true']['es-cl'] = "";
$text['label-true']['es-mx'] = "";
$text['label-true']['fr-ca'] = "";
$text['label-true']['fr-fr'] = "";
$text['label-true']['he-il'] = "";
$text['label-true']['it-it'] = "Vero";
$text['label-true']['nl-nl'] = "";
$text['label-true']['pl-pl'] = "";
$text['label-true']['pt-br'] = "";
$text['label-true']['pt-pt'] = "";
$text['label-true']['ro-ro'] = "";
$text['label-true']['ru-ru'] = "Да";
$text['label-true']['sv-se'] = "sann";
$text['label-true']['uk-ua'] = "";

$text['label-false']['en-us'] = "false";
$text['label-false']['ar-eg'] = "";
$text['label-false']['de-at'] = "aus"; //copied from de-de
$text['label-false']['de-ch'] = "aus"; //copied from de-de
$text['label-false']['de-de'] = "aus";
$text['label-false']['es-cl'] = "falso";
$text['label-false']['es-mx'] = "falso"; //copied from es-cl
$text['label-false']['fr-ca'] = "falso"; //copied from fr-fr
$text['label-false']['fr-fr'] = "falso";
$text['label-false']['he-il'] = "";
$text['label-false']['it-it'] = "Falso";
$text['label-false']['nl-nl'] = "";
$text['label-false']['pl-pl'] = "";
$text['label-false']['pt-br'] = "falso"; //copied from pt-pt
$text['label-false']['pt-pt'] = "falso";
$text['label-false']['ro-ro'] = "";
$text['label-false']['ru-ru'] = "";
$text['label-false']['sv-se'] = "falsk";
$text['label-false']['uk-ua'] = "";

$text['button-add']['en-us'] = "Add";
$text['button-add']['ar-eg'] = "";
$text['button-add']['de-at'] = "Hinzufügen"; //copied from de-de
$text['button-add']['de-ch'] = "Hinzufügen"; //copied from de-de
$text['button-add']['de-de'] = "Hinzufügen";
$text['button-add']['es-cl'] = "";
$text['button-add']['es-mx'] = "";
$text['button-add']['fr-ca'] = "";
$text['button-add']['fr-fr'] = "";
$text['button-add']['he-il'] = "";
$text['button-add']['it-it'] = "Inserire";
$text['button-add']['nl-nl'] = "";
$text['button-add']['pl-pl'] = "";
$text['button-add']['pt-br'] = "";
$text['button-add']['pt-pt'] = "";
$text['button-add']['ro-ro'] = "";
$text['button-add']['ru-ru'] = "Добавить";
$text['button-add']['sv-se'] = "Lägg Till";
$text['button-add']['uk-ua'] = "";

$text['button-edit']['en-us'] = "Edit";
$text['button-edit']['ar-eg'] = "";
$text['button-edit']['de-at'] = "Bearbeiten"; //copied from de-de
$text['button-edit']['de-ch'] = "Bearbeiten"; //copied from de-de
$text['button-edit']['de-de'] = "Bearbeiten";
$text['button-edit']['es-cl'] = "";
$text['button-edit']['es-mx'] = "";
$text['button-edit']['fr-ca'] = "";
$text['button-edit']['fr-fr'] = "";
$text['button-edit']['he-il'] = "";
$text['button-edit']['it-it'] = "Modificare";
$text['button-edit']['nl-nl'] = "";
$text['button-edit']['pl-pl'] = "";
$text['button-edit']['pt-br'] = "";
$text['button-edit']['pt-pt'] = "";
$text['button-edit']['ro-ro'] = "";
$text['button-edit']['ru-ru'] = "Редактировать";
$text['button-edit']['sv-se'] = "Ändra";
$text['button-edit']['uk-ua'] = "";

$text['button-delete']['en-us'] = "Delete";
$text['button-delete']['ar-eg'] = "";
$text['button-delete']['de-at'] = "Löschen"; //copied from de-de
$text['button-delete']['de-ch'] = "Löschen"; //copied from de-de
$text['button-delete']['de-de'] = "Löschen";
$text['button-delete']['es-cl'] = "";
$text['button-delete']['es-mx'] = "";
$text['button-delete']['fr-ca'] = "";
$text['button-delete']['fr-fr'] = "";
$text['button-delete']['he-il'] = "";
$text['button-delete']['it-it'] = "Cancellare";
$text['button-delete']['nl-nl'] = "";
$text['button-delete']['pl-pl'] = "";
$text['button-delete']['pt-br'] = "";
$text['button-delete']['pt-pt'] = "";
$text['button-delete']['ro-ro'] = "";
$text['button-delete']['ru-ru'] = "Удалить";
$text['button-delete']['sv-se'] = "Ta Bort";
$text['button-delete']['uk-ua'] = "";

$text['button-save']['en-us'] = "Save";
$text['button-save']['ar-eg'] = "";
$text['button-save']['de-at'] = "Speichern"; //copied from de-de
$text['button-save']['de-ch'] = "Speichern"; //copied from de-de
$text['button-save']['de-de'] = "Speichern";
$text['button-save']['es-cl'] = "";
$text['button-save']['es-mx'] = "";
$text['button-save']['fr-ca'] = "";
$text['button-save']['fr-fr'] = "";
$text['button-save']['he-il'] = "";
$text['button-save']['it-it'] = "Salva";
$text['button-save']['nl-nl'] = "";
$text['button-save']['pl-pl'] = "";
$text['button-save']['pt-br'] = "Guardar"; //copied from pt-pt
$text['button-save']['pt-pt'] = "Guardar";
$text['button-save']['ro-ro'] = "";
$text['button-save']['ru-ru'] = "Сохранить";
$text['button-save']['sv-se'] = "Spara";
$text['button-save']['uk-ua'] = "";

$text['button-view']['en-us'] = "View";
$text['button-view']['ar-eg'] = "";
$text['button-view']['de-at'] = "Anzeigen"; //copied from de-de
$text['button-view']['de-ch'] = "Anzeigen"; //copied from de-de
$text['button-view']['de-de'] = "Anzeigen";
$text['button-view']['es-cl'] = "";
$text['button-view']['es-mx'] = "";
$text['button-view']['fr-ca'] = "";
$text['button-view']['fr-fr'] = "";
$text['button-view']['he-il'] = "";
$text['button-view']['it-it'] = "Mostra";
$text['button-view']['nl-nl'] = "";
$text['button-view']['pl-pl'] = "";
$text['button-view']['pt-br'] = "";
$text['button-view']['pt-pt'] = "";
$text['button-view']['ro-ro'] = "";
$text['button-view']['ru-ru'] = "";
$text['button-view']['sv-se'] = "Visa";
$text['button-view']['uk-ua'] = "";

$text['button-back']['en-us'] = "Back";
$text['button-back']['ar-eg'] = "";
$text['button-back']['de-at'] = "Zurück"; //copied from de-de
$text['button-back']['de-ch'] = "Zurück"; //copied from de-de
$text['button-back']['de-de'] = "Zurück";
$text['button-back']['es-cl'] = "";
$text['button-back']['es-mx'] = "";
$text['button-back']['fr-ca'] = "";
$text['button-back']['fr-fr'] = "";
$text['button-back']['he-il'] = "";
$text['button-back']['it-it'] = "Indietro";
$text['button-back']['nl-nl'] = "";
$text['button-back']['pl-pl'] = "";
$text['button-back']['pt-br'] = "Voltar"; //copied from pt-pt
$text['button-back']['pt-pt'] = "Voltar";
$text['button-back']['ro-ro'] = "";
$text['button-back']['ru-ru'] = "Назад";
$text['button-back']['sv-se'] = "Tillbaka";
$text['button-back']['uk-ua'] = "";

$text['confirm-delete']['en-us'] = "Do you really want to delete this?";
$text['confirm-delete']['ar-eg'] = "";
$text['confirm-delete']['de-at'] = "Möchten Sie dieses wirklich löschen?"; //copied from de-de
$text['confirm-delete']['de-ch'] = "Möchten Sie dieses wirklich löschen?"; //copied from de-de
$text['confirm-delete']['de-de'] = "Möchten Sie dieses wirklich löschen?";
$text['confirm-delete']['es-cl'] = "";
$text['confirm-delete']['es-mx'] = "";
$text['confirm-delete']['fr-ca'] = "";
$text['confirm-delete']['fr-fr'] = "";
$text['confirm-delete']['he-il'] = "";
$text['confirm-delete']['it-it'] = "Vuoi veramente cancellarlo?";
$text['confirm-delete']['nl-nl'] = "";
$text['confirm-delete']['pl-pl'] = "";
$text['confirm-delete']['pt-br'] = "";
$text['confirm-delete']['pt-pt'] = "";
$text['confirm-delete']['ro-ro'] = "";
$text['confirm-delete']['ru-ru'] = "Вы действительно хотите удалить это?";
$text['confirm-delete']['sv-se'] = "Vill du verkligen ta bort detta?";
$text['confirm-delete']['uk-ua'] = "";

$text['message-add']['en-us'] = "Add Completed";
$text['message-add']['ar-eg'] = "";
$text['message-add']['de-at'] = "Erfolgreich hinzugefügt"; //copied from de-de
$text['message-add']['de-ch'] = "Erfolgreich hinzugefügt"; //copied from de-de
$text['message-add']['de-de'] = "Erfolgreich hinzugefügt";
$text['message-add']['es-cl'] = "";
$text['message-add']['es-mx'] = "";
$text['message-add']['fr-ca'] = "";
$text['message-add']['fr-fr'] = "";
$text['message-add']['he-il'] = "";
$text['message-add']['it-it'] = "Inserimento Completato";
$text['message-add']['nl-nl'] = "";
$text['message-add']['pl-pl'] = "";
$text['message-add']['pt-br'] = "";
$text['message-add']['pt-pt'] = "";
$text['message-add']['ro-ro'] = "";
$text['message-add']['ru-ru'] = "Добавление выполнено";
$text['message-add']['sv-se'] = "Tillagd";
$text['message-add']['uk-ua'] = "";

$text['message-update']['en-us'] = "Update Completed";
$text['message-update']['ar-eg'] = "";
$text['message-update']['de-at'] = "Aktualisierung durchgeführt"; //copied from de-de
$text['message-update']['de-ch'] = "Aktualisierung durchgeführt"; //copied from de-de
$text['message-update']['de-de'] = "Aktualisierung durchgeführt";
$text['message-update']['es-cl'] = "";
$text['message-update']['es-mx'] = "";
$text['message-update']['fr-ca'] = "";
$text['message-update']['fr-fr'] = "";
$text['message-update']['he-il'] = "";
$text['message-update']['it-it'] = "Aggiornamento Completato";
$text['message-update']['nl-nl'] = "";
$text['message-update']['pl-pl'] = "";
$text['message-update']['pt-br'] = "";
$text['message-update']['pt-pt'] = "";
$text['message-update']['ro-ro'] = "";
$text['message-update']['ru-ru'] = "Обновление завершено";
$text['message-update']['sv-se'] = "Ändring Utförd";
$text['message-update']['uk-ua'] = "";

$text['message-delete']['en-us'] = "Delete Completed";
$text['message-delete']['ar-eg'] = "";
$text['message-delete']['de-at'] = "Erfolgreich gelöscht"; //copied from de-de
$text['message-delete']['de-ch'] = "Erfolgreich gelöscht"; //copied from de-de
$text['message-delete']['de-de'] = "Erfolgreich gelöscht";
$text['message-delete']['es-cl'] = "";
$text['message-delete']['es-mx'] = "";
$text['message-delete']['fr-ca'] = "";
$text['message-delete']['fr-fr'] = "";
$text['message-delete']['he-il'] = "";
$text['message-delete']['it-it'] = "Cancellazione Completato";
$text['message-delete']['nl-nl'] = "";
$text['message-delete']['pl-pl'] = "";
$text['message-delete']['pt-br'] = "";
$text['message-delete']['pt-pt'] = "";
$text['message-delete']['ro-ro'] = "";
$text['message-delete']['ru-ru'] = "Удаление завершено";
$text['message-delete']['sv-se'] = "Borttagen";
$text['message-delete']['uk-ua'] = "";

$text['message-required']['en-us'] = "Please provide: ";
$text['message-required']['ar-eg'] = "";
$text['message-required']['de-at'] = "Bitte geben Sie folgendes an:"; //copied from de-de
$text['message-required']['de-ch'] = "Bitte geben Sie folgendes an:"; //copied from de-de
$text['message-required']['de-de'] = "Bitte geben Sie folgendes an:";
$text['message-required']['es-cl'] = "";
$text['message-required']['es-mx'] = "";
$text['message-required']['fr-ca'] = "";
$text['message-required']['fr-fr'] = "";
$text['message-required']['he-il'] = "";
$text['message-required']['it-it'] = "Prego fornire:";
$text['message-required']['nl-nl'] = "";
$text['message-required']['pl-pl'] = "";
$text['message-required']['pt-br'] = "";
$text['message-required']['pt-pt'] = "";
$text['message-required']['ro-ro'] = "";
$text['message-required']['ru-ru'] = "Пожалуйста предоставьте: ";
$text['message-required']['sv-se'] = "Var god ange: ";
$text['message-required']['uk-ua'] = "";

?>
